config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.draw do
    root :to => 'users#index'

    resources :sessions
    resources :user_mailer

    resources :users

    resources :questions do
      resources :answers


    end
    get "/log-in" => "sessions#new"
    post "/log-in" => "sessions#create"
    get "/log-out" => "sessions#destroy", as: :log_out

  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :votes
  validates :description, presence: true
  Answer.order(:cached_weighted_average => :desc)
  acts_as_votable

def up_votes
    self.votes.where(value: 1).count
  end

  def down_votes
    self.votes.where(value: -1).count
  end
  def points
    self.votes.sum(:value).to_i
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  validates :description, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password

  has_many :questions
  has_many :votes


  validates :name, :email, :presence => true
  validates_uniqueness_of :name

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(self.password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(:email => email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      return user
    else
      return nil
    end
  end
end

app/models/votes.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :answer
   validates :value, inclusion: {in: [1, -1]}

 def create
    @upvote = Upvote.new(secure_params)
    @upvote.answer = Answer.find(params[:answet_id, :user_id])
    if @upvote.save
      respond_to do |format|
        format.html { redirect_to @upvote.answer }
        format.js # we'll use this later for AJAX!
      end
    end
  end

  private
    def secure_params
      params.require(:upvote).permit(:user)
    end
end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def send_response_message
    CustomerMailer.deliver_response_message(self)
  end
<<<<<<< HEAD
=======

>>>>>>> d4c124ae07a38bc2e24ad049073ef0a97e12bcd8

  def new
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    UserMailer.response_email(@answer).deliver_now
    if @answer.save
      UserMailer.response_email(@answer).deliver_now
      flash[:notice] = "Thanks for your answer."
      redirect_to questions_path(@answer.question)
    else
      flash[:notice] = "Error in answer submission."
      render :new
    end
  end


  def edit
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
  end

  def destroy
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    @answer.destroy
    flash[:notice] = "Your answer has been removed."
    redirect_to question_path(@question)
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    if @answer.update(params[:answer])
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def answer_params
    params.require(:answer).permit(:description, :user_id, :question_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    if @question.save
      redirect_to questions_path
    else
      render :new
    end
  end


  def show
    @questions = Question.all
    @question = Question.find(params[:id])
    @user = User.find(@question.user_id)
    render :show
  end

  def edit
    @question = Question.find(params[:id])
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    flash[:notice] = "Your question has been removed."
    redirect_to questions_path
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to questions_path
    else
      render :edit
    end
  end
  
private
  def question_params
    params.require(:question).permit(:description, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    if User.authenticate(params[:email], params[:password])
      @user = User.find_by(:email => params[:email])
      session[:user_id] = @user.id
      current_user = User.find(@user.id)
      flash[:notice] = "You have logged in to Foto Friends, the hot new website!"
      redirect_to "/"
    else
      flash[:alert] = "Try Again"
      redirect_to log_in_path
    end
  end


  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been logged out... fare thee well..."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def send_welcome_message
    CustomerMailer.deliver_welcome_message(self)
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @questions = Question.all
<<<<<<< HEAD
=======

>>>>>>> d4c124ae07a38bc2e24ad049073ef0a97e12bcd8
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.welcome_email(@user).deliver_now
      flash[:notice] = "Registered Sucessfully!!"
      redirect_to users_path
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "Smell you later, user."
    redirect_to users_path
  end

  def update
    @user = User.find(params[:id])
    if @user.update(params[:user])
      redirect_to users_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_form.html.erb
<%= render "layouts/errors", :object => @answer %>

<%= form_for [@user, @question, @answer] do |f| %>
<%= f.text_field :description %>

<%= f.submit "Post Your Response" %>
<% end %>

app/views/answers/edit.html.erb
<h1>Edit your answer!</h1>

<%= render 'form' %>

app/views/answers/new.html.erb
<h1>Got an Answer?</h1>
<%=  render 'form' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Oops there were some errors. Please try again:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StackClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= render "layouts/errors", :object => @question %>

<%= form_for [@user, @question] do |f| %>
<%= f.text_field :description %>

<%= f.submit "Post Your Question" %>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit your question!</h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Tucker's Overflow Questions</h1>
  </div>
</div>

  <% if @questions.any? %>

    <ul>

      <% @questions.each do |question| %>

        <li>
<<<<<<< HEAD
        <%= link_to question.description, question_path(question) %>
=======
        <%= link_to question_path(question) do %><%= question.description %><% end %>
>>>>>>> d4c124ae07a38bc2e24ad049073ef0a97e12bcd8
        </li>

      <% end %>

    </ul>
  <% end %>

    <p><%= link_to "Add a new question", new_question_path %></p>
    <p><%= link_to "Return to Homepage", users_path(@user) %></p>

app/views/questions/new.html.erb
<h1>Post your question %></h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Question</h1>
  </div>
</div>
  <ul>
      <%= @question.description %>
  </ul>

<div class="row">
  <div class="col-md-6">
    <% if @question.answers.any? %>

    <h4>Here are the answers for this question:</h4>
    <ul>
      <% @question.answers.each do |answer| %>
      <li>
        <%= link_to answer.description, question_answers_path(@question, answer) %>
          <% end %>
  </div>
</div>

      </li>
        <% end %>
      </ul>
    </div>
  </div>

  <% else %>
  <div class="row">
    <div class="col-md-12 center">
      <p>There are no answers yet!</p>
      <% end %>

      <p><%= link_to "Add a answer", new_question_answer_path(@question) %></p>
      <p><%= link_to "Return to questions", questions_path %></p>
      </div>
    </div>
<<<<<<< HEAD
<p><%= link_to "Return to Homepage", user_path(@user) %></p>
=======
      <p><%= link_to "Return to Homepage", users_path(@user) %></p>
>>>>>>> d4c124ae07a38bc2e24ad049073ef0a97e12bcd8

app/views/users/_form.html.erb
<%= render "layouts/errors", :object => @user %>

<%= form_for @user do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%=f.label :email %>
<%=f.text_field :email %>
<%=f.label :password %>
<%=f.password_field :password %>
<%=f.label :password_confirmation %>
<%=f.password_field :password_confirmation %>
<%= f.submit "Sign Up" %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 center">
      <h1>Accounts</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <% if current_user %>
        <p> You are logged in as <h2><%= link_to current_user[:name], user_path(current_user) %></h2> </p>
      <% end %>
        <p>  <%= link_to "log-out", log_out_path %></p>
        <p><%= link_to "Register New Account", new_user_path %>
        </p>
        <p>

          <%= link_to "Login to an Existing Account", log_in_path %>
        </p>
      </div>
    </div>
</div>

app/views/users/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-12">
      <h4><%= @user.name %></h4>
  </div>
</div>
  <h1>Your Questions</h1>

    <% if @user.questions.any? %>

    <h4>Questions you have asked:</h4>
      <ul>
        <% @user.questions.each do |question| %>
          <li>
            <%= link_to question.description, question_path(@user, question) %> |
            <%= link_to "Edit", edit_question_path(@user, question) %> |
            <%= link_to "Delete", question_path(@user, question),
            :data => {:confirm => "Are you sure?",
              :method => "delete"} %>
            </li>
        <% end %>

        </ul>
      <% end %>

        <h1>All Questions</h1>

        <% if @questions.any? %>
          <ul>
            <% @questions.each do |question| %>
          <li>
<<<<<<< HEAD
            <%= link_to question.description, questions_path(@question) %>
=======
            <%= link_to question.description, question_path(question) %>
>>>>>>> d4c124ae07a38bc2e24ad049073ef0a97e12bcd8
          </li>
        <% end %>
          </ul>
        <% else %>
          <p>There are no questions yet!</p>

          <p><%= link_to "Add a new question", new_question_path %></p>
          <p><%= link_to "Edit", edit_user_path(@user) %></p>
          <p><%= link_to "Delete", user_path(@user),
          :data => {:confirm => "You sure?",
            :method => "delete"} %></p>
        <% end %>
<<<<<<< HEAD
        <p><%= link_to "Return to Homepage", user_path(@user) %></p>
=======
        <p><%= link_to "Return to Homepage", users_path(@user) %></p>
>>>>>>> d4c124ae07a38bc2e24ad049073ef0a97e12bcd8